version: '3.7'
services:
    frontend:
        container_name: frontend
        build:
            context: ./ui
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - "backend"
        environment:
            - REACT_APP_API_URL=http://PatientManagerBackend:8080
            - REACT_APP_PORT=3000
    backend:
        container_name: backend
        hostname: PatientManagerBackend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 8080:8080
